language: csharp
sudo: required
dist: trusty
dotnet: 2.0.0
solution: NReco.Text.AhoCorasickDoubleArrayTrie.sln 

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

script:
- dotnet restore NReco.Text.AhoCorasickDoubleArrayTrie.sln
- dotnet test test\NReco.Text.AhoCorasickDoubleArrayTrie.Tests\NReco.Text.AhoCorasickDoubleArrayTrie.Tests.csproj --configuration Release
