language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0

script:
- dotnet restore NReco.Text.AhoCorasickDoubleArrayTrie.sln
- dotnet test test/NReco.Text.AhoCorasickDoubleArrayTrie.Tests/NReco.Text.AhoCorasickDoubleArrayTrie.Tests.csproj --configuration Release
